
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuyhmqaejfnvklkthmmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eWhtcWFlamZudmtsa3RobW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTI0NDUsImV4cCI6MjA1ODIyODQ0NX0.6C7XT5WLR6amYW-tUVYPuF0s1WiE4zO_r2aaVtVdT3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
